name: francinebassetti deployment

on: 
    push:
        branches: [main]

    workflow_dispatch:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building the project..."

    # Deploy to Development
    deploy-development:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: development
            url: ${{ vars.URL }}
        steps:
            - name: Deploy to Development
              uses: actions/checkout@v2
            # - name: Service Deployment
            #   uses: easinthemes/ssh-deploy@main
            #   with: 
            #     SSH_PRIVATE_KEY: $ {{ secrets.SERVER_SSH_KEY }}
            #     ARGS: "-rlgoDzvc --delete"
            #     SOURCE: "public/"
            #     REMOTE_HOST: $ {{ vars.REMOTE_HOST }}
            #     REMOTE_USER: $ {{ vars.REMOTE_USER }}
            #     REMOTE_PORT: $ {{ vars.REMOTE_PORT }}
            #     TARGET: $ {{ vars.REMOTE_TARGET }}

    # Deploy to Staging
    deploy-staging:
        runs-on: ubuntu-latest
        needs: deploy-development
        environment: 
            name: staging
            url: ${{ vars.URL }}
        steps:
            - name: Deploy to staging
              uses: actions/checkout@v2

    
    # Deploy to Production
    deploy-production:
        runs-on: ubuntu-latest
        needs: deploy-staging
        environment: 
            name: production
            url: ${{ vars.URL }}
        steps:
            - name: Deploy to production
              uses: actions/checkout@v2