name: francinebassetti deployment

on: 
  push:
    branches: [main]

  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project..."

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build React
        run: |
          cd cms
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin main
            source backend/venv/bin/activate
            pip install -r backend/requirements.txt
            python backend/backend/manage.py migrate
            python backend/backend/manage.py collectstatic --noinput
            systemctl restart gunicorn  # Reinicia o Django
            cp -r frontend/build/* /var/www/  # Move arquivos do React
  
  # Deploy to Production
  production:
    runs-on: ubuntu-latest
    needs: deploy
    environment: 
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Deploy to production
        uses: actions/checkout@v2