name: francinebassetti deployment

on: 
  push:
    branches: [main]

  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project..."

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: cms/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('cms/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies and build React
        run: |
          cd cms
          npm install
          npm run build

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Python dependencies
        run: |
          pip install -r backend/requirements.txt


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            set -e  # para parar em qualquer erro
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin main
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python backend/manage.py migrate
            python backend/manage.py collectstatic --noinput
            cp -r cms/build/* /var/www/  # Move arquivos do React
            
  # Deploy to Production
  production:
    runs-on: ubuntu-latest
    needs: deploy
    environment: 
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Deploy to production
        uses: actions/checkout@v2
